# Project configuration
group = org.calypsonet.keyple

# Java Configuration
jvmToolchainVersion = 17
javaSourceLevel = 17
javaTargetLevel = 17

# Ensure Gradle JVM uses UTF-8 encoding for consistent file reading/writing across all environments
org.gradle.jvmargs = -Dfile.encoding=UTF-8

# Kotlin code style for this project ("official" or "obsolete"): use the official Kotlin coding conventions
kotlin.code.style = official
