name: Build and Test

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  # ========================================
  # ANDROID APPLICATIONS
  # ========================================

  build-ticketing-control-app:
    name: "Ticketing Control App (Android)"
    uses: ./.github/workflows/reusable-android-gradle-build.yml
    with:
      component-name: "Ticketing Control App"
      working-directory: "./src/control/"

  build-reloading-multiplatform-client-android-macos:
    name: "Reloading Multiplatform Client (Android on macOS)"
    uses: ./.github/workflows/reusable-android-gradle-build.yml
    with:
      component-name: "Reloading Multiplatform Client"
      working-directory: "./src/reloading-remote/client/interop-mobile-multiplatform/"
      target-os: "macos-latest"

  build-reloading-keyple-client-android:
    name: "Reloading Keyple Client (Android)"
    uses: ./.github/workflows/reusable-android-gradle-build.yml
    with:
      component-name: "Reloading Keyple Client"
      working-directory: "./src/reloading-remote/client/keyple-mobile-android/"

  build-validation-app:
    name: "Validation App (Android)"
    uses: ./.github/workflows/reusable-android-gradle-build.yml
    with:
      component-name: "Validation App"
      working-directory: "./src/validation/"

  # ========================================
  # SERVER APPLICATION
  # ========================================

  build-reloading-server:
    name: "Reloading Server (Java + Node.js)"
    uses: ./.github/workflows/reusable-java-node-hybrid-build.yml
    with:
      component-name: "Reloading Server"
      working-directory: "./src/reloading-remote/server/"
      node-directory: "./dashboard-app"

  # ========================================
  # .NET APPLICATIONS
  # ========================================

  build-reloading-dotnet-client:
    name: "Reloading .NET Client (Windows)"
    uses: ./.github/workflows/reusable-dotnet-build.yml
    with:
      component-name: "Reloading .NET Client"
      working-directory: "./src/reloading-remote/client/pc-dotnet/"
      archive-name-prefix: "keyple-demo-ticketing-reloading-pc-dotnet-app"