name: CI on main and PR

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  # ========================================
  # ANDROID APPLICATIONS
  # ========================================

  ci-control-app:
    name: "Control (Android)"
    uses: ./.github/workflows/reusable-android-ci.yml
    with:
      component-name: "Control App"
      working-directory: "./src/control/"

  ci-reloading-multiplatform-client-android-macos:
    name: "Reloading Client KMP (Android/macOS)"
    uses: ./.github/workflows/reusable-android-ci.yml
    with:
      component-name: "Reloading Multiplatform Client"
      working-directory: "./src/reloading-remote/client/interop-mobile-multiplatform/"
      target-os: "macos-latest"

  ci-reloading-keyple-client-android:
    name: "Reloading Client (Android)"
    uses: ./.github/workflows/reusable-android-ci.yml
    with:
      component-name: "Reloading Keyple Client"
      working-directory: "./src/reloading-remote/client/keyple-mobile-android/"

  ci-validation-app:
    name: "Validation (Android)"
    uses: ./.github/workflows/reusable-android-ci.yml
    with:
      component-name: "Validation App"
      working-directory: "./src/validation/"

  # ========================================
  # SERVER APPLICATION
  # ========================================

  ci-reloading-server:
    name: "Reloading Server (Java+Node)"
    uses: ./.github/workflows/reusable-java-node-ci.yml
    with:
      component-name: "Reloading Server"
      working-directory: "./src/reloading-remote/server/"
      node-directory: "./dashboard-app"

  # ========================================
  # .NET APPLICATIONS
  # ========================================

  ci-reloading-dotnet-client:
    name: "Reloading Client (.NET/Windows)"
    uses: ./.github/workflows/reusable-dotnet-ci.yml
    with:
      component-name: "Reloading .NET Client"
      working-directory: "./src/reloading-remote/client/pc-dotnet/"