name: CI on main and PR

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  # ========================================
  # ANDROID APPLICATIONS
  # ========================================

  ci-control:
    name: "Control (Android)"
    uses: ./.github/workflows/reusable-android-ci.yml
    with:
      component-name: "Control"
      working-directory: "./src/control/"

  ci-reloading-kmp-android-macos:
    name: "Reloading Client KMP (Android/macOS)"
    uses: ./.github/workflows/reusable-kmp-android-ios-ci.yml
    with:
      component-name: "Reloading Client Interop Mobile Multiplatform"
      working-directory: "./src/reloading-remote/client/interop-mobile-multiplatform/"

  ci-reloading-android:
    name: "Reloading Client (Android)"
    uses: ./.github/workflows/reusable-android-ci.yml
    with:
      component-name: "Reloading Client Keyple Mobile Android"
      working-directory: "./src/reloading-remote/client/keyple-mobile-android/"

  ci-validation:
    name: "Validation (Android)"
    uses: ./.github/workflows/reusable-android-ci.yml
    with:
      component-name: "Validation"
      working-directory: "./src/validation/"

  # ========================================
  # SERVER APPLICATION
  # ========================================

  ci-reloading-server:
    name: "Reloading Server (Java+Node)"
    uses: ./.github/workflows/reusable-java-node-ci.yml
    with:
      component-name: "Reloading Server"
      working-directory: "./src/reloading-remote/server/"
      node-directory: "./dashboard-app"

  # ========================================
  # .NET APPLICATIONS
  # ========================================

  ci-reloading-dotnet:
    name: "Reloading Client (.NET/Windows)"
    uses: ./.github/workflows/reusable-dotnet-ci.yml
    with:
      component-name: "Reloading Client PC .NET"
      working-directory: "./src/reloading-remote/client/pc-dotnet/"