name: Release tag

on:
  release:
    types:
      - published
  workflow_dispatch:

jobs:
  # ========================================
  # ANDROID APPLICATIONS
  # ========================================

  release-control-app:
    name: "Control (Android)"
    uses: ./.github/workflows/reusable-android-release.yml
    with:
      component-name: "Control App"
      working-directory: "./src/control/"

  release-reloading-multiplatform-client-android:
    name: "Reloading Client KMP (Android)"
    uses: ./.github/workflows/reusable-android-release.yml
    with:
      component-name: "Reloading Multiplatform Client"
      working-directory: "./src/reloading-remote/client/interop-mobile-multiplatform/"
      apk-output-path: "composeApp/build/outputs/apk/debug/*.apk"

  release-reloading-keyple-client-android:
    name: "Reloading Client (Android)"
    uses: ./.github/workflows/reusable-android-release.yml
    with:
      component-name: "Reloading Keyple Client"
      working-directory: "./src/reloading-remote/client/keyple-mobile-android/"

  release-validation-app:
    name: "Validation (Android)"
    uses: ./.github/workflows/reusable-android-release.yml
    with:
      component-name: "Validation App"
      working-directory: "./src/validation/"

  # ========================================
  # SERVER APPLICATION
  # ========================================

  release-reloading-server:
    name: "Reloading Server (Java+Node)"
    uses: ./.github/workflows/reusable-java-node-release.yml
    with:
      component-name: "Reloading Server"
      working-directory: "./src/reloading-remote/server/"
      node-directory: "./dashboard-app"

  # ========================================
  # DESKTOP APPLICATIONS - MULTIPLATFORM
  # ========================================

  release-reloading-multiplatform-client-macos:
    name: "Reloading Client KMP (macOS)"
    uses: ./.github/workflows/reusable-multiplatform-desktop-release.yml
    with:
      component-name: "Reloading Multiplatform Client"
      target-os: "macos-latest"
      platform-name: "macOS"
      working-directory: "./src/reloading-remote/client/interop-mobile-multiplatform/"
      platform-artifact-pattern: "composeApp/build/compose/binaries/main/dmg/*.dmg"

  release-reloading-multiplatform-client-linux:
    name: "Reloading Client KMP (Linux)"
    uses: ./.github/workflows/reusable-multiplatform-desktop-release.yml
    with:
      component-name: "Reloading Multiplatform Client"
      target-os: "ubuntu-latest"
      platform-name: "Linux"
      working-directory: "./src/reloading-remote/client/interop-mobile-multiplatform/"
      platform-artifact-pattern: "composeApp/build/compose/binaries/main/deb/*.deb"

  release-reloading-multiplatform-client-windows:
    name: "Reloading Client KMP (Windows)"
    uses: ./.github/workflows/reusable-multiplatform-desktop-release.yml
    with:
      component-name: "Reloading Multiplatform Client"
      target-os: "windows-latest"
      platform-name: "Windows"
      working-directory: "./src/reloading-remote/client/interop-mobile-multiplatform/"
      platform-artifact-pattern: "composeApp/build/compose/binaries/main/msi/*.msi"

  # ========================================
  # .NET APPLICATIONS
  # ========================================

  release-reloading-dotnet-client:
    name: "Reloading Client (.NET/Windows)"
    uses: ./.github/workflows/reusable-dotnet-release.yml
    with:
      component-name: "Reloading .NET Client"
      working-directory: "./src/reloading-remote/client/pc-dotnet/"
      archive-name-prefix: "kdt-reloading-pc-dotnet-app"