name: Release tag

on:
  release:
    types:
      - published
  workflow_dispatch:

jobs:
  # ========================================
  # ANDROID APPLICATIONS
  # ========================================

  release-control:
    name: "Control (Android)"
    uses: ./.github/workflows/reusable-android-release.yml
    with:
      component-name: "Control"
      working-directory: "./src/control/"

  release-reloading-kmp-android:
    name: "Reloading Client KMP (Android)"
    uses: ./.github/workflows/reusable-android-release.yml
    with:
      component-name: "Reloading Client Interop Mobile Multiplatform"
      working-directory: "./src/reloading-remote/client/interop-mobile-multiplatform/"
      apk-output-path: "composeApp/build/outputs/apk/debug/*.apk"

  release-reloading-android:
    name: "Reloading Client (Android)"
    uses: ./.github/workflows/reusable-android-release.yml
    with:
      component-name: "Reloading Client Keyple Mobile Android"
      working-directory: "./src/reloading-remote/client/keyple-mobile-android/"

  release-validation:
    name: "Validation (Android)"
    uses: ./.github/workflows/reusable-android-release.yml
    with:
      component-name: "Validation"
      working-directory: "./src/validation/"

  # ========================================
  # SERVER APPLICATION
  # ========================================

  release-reloading-server:
    name: "Reloading Server (Java+Node)"
    uses: ./.github/workflows/reusable-java-node-release.yml
    with:
      component-name: "Reloading Server"
      working-directory: "./src/reloading-remote/server/"
      node-directory: "./dashboard-app"

  # ========================================
  # DESKTOP APPLICATIONS - MULTIPLATFORM
  # ========================================

  release-reloading-kmp-macos:
    name: "Reloading Client KMP (macOS)"
    uses: ./.github/workflows/reusable-kmp-desktop-release.yml
    with:
      component-name: "Reloading Client Interop Mobile Multiplatform"
      target-os: "macos-latest"
      platform-name: "macOS"
      working-directory: "./src/reloading-remote/client/interop-mobile-multiplatform/"
      platform-artifact-pattern: "composeApp/build/compose/binaries/main/dmg/*.dmg"

  release-reloading-kmp-linux:
    name: "Reloading Client KMP (Linux)"
    uses: ./.github/workflows/reusable-kmp-desktop-release.yml
    with:
      component-name: "Reloading Client Interop Mobile Multiplatform"
      target-os: "ubuntu-latest"
      platform-name: "Linux"
      working-directory: "./src/reloading-remote/client/interop-mobile-multiplatform/"
      platform-artifact-pattern: "composeApp/build/compose/binaries/main/deb/*.deb"

  release-reloading-kmp-windows:
    name: "Reloading Client KMP (Windows)"
    uses: ./.github/workflows/reusable-kmp-desktop-release.yml
    with:
      component-name: "Reloading Client Interop Mobile Multiplatform"
      target-os: "windows-latest"
      platform-name: "Windows"
      working-directory: "./src/reloading-remote/client/interop-mobile-multiplatform/"
      platform-artifact-pattern: "composeApp/build/compose/binaries/main/msi/*.msi"

  # ========================================
  # .NET APPLICATIONS
  # ========================================

  release-reloading-dotnet:
    name: "Reloading Client (.NET/Windows)"
    uses: ./.github/workflows/reusable-dotnet-release.yml
    with:
      component-name: "Reloading Client PC .NET"
      working-directory: "./src/reloading-remote/client/pc-dotnet/"
      archive-name-prefix: "kdt-reloading-pc-dotnet-app"