name: Reusable .NET CI

on:
  workflow_call:
    inputs:
      component-name:
        description: 'Name of the component being built'
        required: true
        type: string
      working-directory:
        description: 'Working directory for the build'
        required: true
        type: string

jobs:
  ci-dotnet:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code from ${{ github.repository }}/${{ github.ref }}
        uses: actions/checkout@v4
        with:
          lfs: true

      - name: Setup .NET 7.0.x
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 7.0.x

      - name: Check code format, build and test ${{ inputs.component-name }}
        working-directory: ./src/reloading-remote/client/pc-dotnet
        run: |
          dotnet restore
          dotnet format --verify-no-changes App.sln
          dotnet build --no-restore
          dotnet test --no-build --verbosity normal
