name: Reusable Android Gradle Release

on:
  workflow_call:
    inputs:
      component-name:
        description: 'Name of the component being built'
        required: true
        type: string
      working-directory:
        description: 'Working directory for the build'
        required: true
        type: string
      apk-output-path:
        description: 'Path to APK outputs relative to working directory'
        required: false
        type: string
        default: 'app/build/outputs/apk/debug/*.apk'

jobs:
  release-android:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code from ${{ github.repository }}/${{ github.ref }}
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Update permissions for ${{ inputs.component-name }}
        working-directory: .
        run: chmod +x ${{ inputs.working-directory }}/gradlew

      - name: Build ${{ inputs.component-name }} artifacts
        env:
          ORG_GRADLE_PROJECT_releaseTag: ${{ github.event.release.tag_name }}
        working-directory: ${{ inputs.working-directory }}
        run: ./gradlew spotlessCheck testDebugUnitTest assembleDebug

      - name: Collect ${{ inputs.component-name }} artifacts
        working-directory: ${{ inputs.working-directory }}
        run: |
          mkdir -p release-artifacts
          cp ${{ inputs.apk-output-path }} release-artifacts/ || true

      - name: Upload ${{ inputs.component-name }} artifacts to GitHub release
        uses: softprops/action-gh-release@v2
        with:
          files: ${{ inputs.working-directory }}/release-artifacts/*
          token: ${{ secrets.GITHUB_TOKEN }}
