name: Reusable Java + Node.js Release

on:
  workflow_call:
    inputs:
      component-name:
        description: 'Name of the component being built'
        required: true
        type: string
      working-directory:
        description: 'Working directory for the build'
        required: true
        type: string
      node-directory:
        description: 'Directory containing Node.js project relative to working directory'
        required: true
        type: string

jobs:
  release-java-node:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code from ${{ github.repository }}/${{ github.ref }}
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Set up Node.js 16
        uses: actions/setup-node@v4
        with:
          node-version: 16

      - name: Update permissions for ${{ inputs.component-name }}
        working-directory: .
        run: chmod +x ${{ inputs.working-directory }}/gradlew

      - name: Build ${{ inputs.component-name }} artifacts
        env:
          ORG_GRADLE_PROJECT_releaseTag: ${{ github.event.release.tag_name }}
        working-directory: ${{ inputs.working-directory }}
        run: |
          cd ${{ inputs.node-directory }}
          npm install
          cd ..
          ./gradlew build

      - name: Collect ${{ inputs.component-name }} artifacts
        working-directory: ${{ inputs.working-directory }}
        run: |
          mkdir -p release-artifacts
          cp build/*-full.jar release-artifacts/ || true

      - name: Upload ${{ inputs.component-name }} artifacts to GitHub release
        uses: softprops/action-gh-release@v2
        with:
          files: ${{ inputs.working-directory }}/release-artifacts/*
          token: ${{ secrets.GITHUB_TOKEN }}
