name: Reusable Android Gradle CI

on:
  workflow_call:
    inputs:
      component-name:
        description: 'Name of the component being built'
        required: true
        type: string
      working-directory:
        description: 'Working directory for the build'
        required: true
        type: string
      target-os:
        description: 'Target OS (ubuntu-latest, macos-latest, windows-latest)'
        required: false
        type: string
        default: 'ubuntu-latest'

jobs:
  ci-android:
    runs-on: ${{ inputs.target-os }}
    steps:
      - name: Check out repository code from ${{ github.repository }}/${{ github.ref }}
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Update permissions for ${{ inputs.component-name }}
        working-directory: .
        run: chmod +x ${{ inputs.working-directory }}/gradlew

      - name: Build ${{ inputs.component-name }} artifacts
        working-directory: ${{ inputs.working-directory }}
        run: ./gradlew spotlessCheck testDebugUnitTest assembleDebug
