name: Reusable KMP Android + iOS CI

on:
  workflow_call:
    inputs:
      component-name:
        description: 'Name of the component being built'
        required: true
        type: string
      working-directory:
        description: 'Working directory for the build'
        required: true
        type: string

jobs:
  ci-kmp-android-ios:
    runs-on: macos-latest
    steps:
      - name: Check out repository code from ${{ github.repository }}/${{ github.ref }}
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Update permissions for ${{ inputs.component-name }}
        working-directory: .
        run: chmod +x ${{ inputs.working-directory }}/gradlew

      - name: Build ${{ inputs.component-name }} artifacts
        working-directory: ${{ inputs.working-directory }}
        run: ./gradlew spotlessCheck testDebugUnitTest assembleDebug linkDebugFrameworkIosArm64 linkDebugFrameworkIosX64 linkDebugFrameworkIosSimulatorArm64
